# Generated by Django 3.2.5 on 2021-09-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='subtotal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
