# Generated by Django 3.2.5 on 2021-09-06 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210906_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='subtotal',
        ),
    ]
