# Generated by Django 3.2.5 on 2021-09-06 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210906_1858'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Total',
        ),
    ]
